### ISSUE TITLE
Js

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gamabuntat/fsd-step-2#7]
1. Конструкторы класса должны быть максимально легковесными 
[вот](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.12)
![image](https://user-images.githubusercontent.com/89850975/132404397-5fcb80a6-7d42-4872-bf41-d9984c98e54f.png)
2. Название классов лучше хранить в переменных  
![image](https://user-images.githubusercontent.com/89850975/132405232-0029a738-a716-49de-b50d-38cc142b777e.png)
3. При обращении к DOM через класс он должен начинаться с **js** [вот](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.1)
4. Название классов компонентов должно быть в CamelCase 
![image](https://user-images.githubusercontent.com/89850975/132406129-7b6d2975-f907-41ef-b0bf-7ffd65c55411.png)
5. Каждый класс компонент должке быть отдельным независимым модулем, который вызывается в файле indes.js компоненты либо `НазваниеКомпоненты-init.js`
![image](https://user-images.githubusercontent.com/89850975/132406330-0f85f94c-6c0c-4541-8ff8-0cd43b40fb64.png)
Так нельзя. [Про модульность](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.5)
Все issue которые оставляю исправляй и во втором проекте

**Comment by gamabuntat** [comment]
[commit](https://github.com/gamabuntat/fsd-step-2/commit/1c46559cd4e12b50ae4586437c931fa248c2bf95)
Здравствуйте! Вот так нормально иниты компонентов оформлять?

**Comment by ArsenGadjiusmanov** [comment]
Еще добавлю класс в компоненте должен быть 1, а в calendar у тебя лежит еще класс Table 

По поводу правильности 
https://github.com/gamabuntat/fsd-step-2/blob/b0f495e575d0054e5f427b790351dae6c4114445/src/library.blocks/calendar/calendar-init.js#L3-L8
Здесь ты возвращаешь функцию, которую можно вызвать и которая про инициализирует календарь. А надо чтоб календарь инициализировался сам при подключении. В JQ есть удобная функция $(()=>{ _твой код_ }) такой способ гарантирует тебе, что код выполнится только после загрузки DOM и необходимые классы будут на странице

**Comment by gamabuntat** [comment]
> Еще добавлю класс в компоненте должен быть 1, а в calendar у тебя лежит еще класс Table

Мне нужно для Table создать отдельный компонент?

**Comment by ArsenGadjiusmanov** [comment]
Для js по нашим бест практис следует использовать одинарные кавычки. js в pug не является исключением.
![image](https://user-images.githubusercontent.com/89850975/134765152-aa1b161c-95ea-4e3d-9f9a-b4675d8cf366.png)

Export лучше выносить в конец  вот пункт в бп [тык](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.18)
![image](https://user-images.githubusercontent.com/89850975/134767069-1acc4018-a895-4f4d-a956-0b08ae6670b4.png)

Помимо наших стандартов мы еще используем стандарты [airbnb ](https://github.com/airbnb/javascript)
[Пробелы между квадратными скобками и их содержимым](https://github.com/leonidlebedev/javascript-airbnb#whitespace--in-brackets) 
![image](https://user-images.githubusercontent.com/89850975/134767359-bb990f2c-4e0e-4ec9-a247-0247733f3b9b.png)
[Пробелы между фигурными скобками и их содержимым](https://github.com/leonidlebedev/javascript-airbnb#whitespace--in-braces)
![image](https://user-images.githubusercontent.com/89850975/134767451-023b679c-e73a-42ff-940d-2bbbded63a78.png)

![image](https://user-images.githubusercontent.com/89850975/134767405-0ee6e16c-4e58-4131-afb6-bea94730bc76.png)

**Comment by gamabuntat** [comment]
> Для js по нашим бест практис следует использовать одинарные кавычки. js в pug не является исключением.
> ![image](https://user-images.githubusercontent.com/89850975/134765152-aa1b161c-95ea-4e3d-9f9a-b4675d8cf366.png)
> 
> Export лучше выносить в конец вот пункт в бп [тык](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.18)
> ![image](https://user-images.githubusercontent.com/89850975/134767069-1acc4018-a895-4f4d-a956-0b08ae6670b4.png)
> 
> Помимо наших стандартов мы еще используем стандарты [airbnb ](https://github.com/airbnb/javascript)
> [Пробелы между квадратными скобками и их содержимым](https://github.com/leonidlebedev/javascript-airbnb#whitespace--in-brackets)
> ![image](https://user-images.githubusercontent.com/89850975/134767359-bb990f2c-4e0e-4ec9-a247-0247733f3b9b.png)
> [Пробелы между фигурными скобками и их содержимым](https://github.com/leonidlebedev/javascript-airbnb#whitespace--in-braces)
> ![image](https://user-images.githubusercontent.com/89850975/134767451-023b679c-e73a-42ff-940d-2bbbded63a78.png)
> 
> ![image](https://user-images.githubusercontent.com/89850975/134767405-0ee6e16c-4e58-4131-afb6-bea94730bc76.png)

А в миксине дефолтные пареметры должны с одинарными кавычками быть?

**Comment by ArsenGadjiusmanov** [comment]
> А в миксине дефолтные пареметры должны с одинарными кавычками быть?

в дефолтных параметрах двойные. Там где начинается js через - одинарные

**Comment by gamabuntat** [comment]
12434457790063ba721896a612628bf82bfb38ec
