### ISSUE TITLE
Структура папок

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gamabuntat/fsd-step-2#8]
1. Почему в папке pages лежит папка img? И почему в pages еще один pages ?? Сделай структуру более плоской  
![image](https://user-images.githubusercontent.com/89850975/132407048-a56bebb5-e6ff-4627-83c8-40964ffc049b.png)
2. У тебя лежат файлы которые никак не используются 
![image](https://user-images.githubusercontent.com/89850975/132407517-a749f283-6d86-4ed1-990d-7196834e37b5.png)
3. 
![image](https://user-images.githubusercontent.com/89850975/132408054-1b41a338-aabd-449c-88e2-045fc64dc6fd.png)
в local на компьютере пользователя ищется шрифт с названием ввиде смайлика

**Comment by gamabuntat** [comment]
Забыл хештег df77e2280eafab14a78a1c6fbce2c6a8b656ef52

**Comment by ArsenGadjiusmanov** [comment]
По поводу папок еще добавлю. Для именования папок с большими названиями мы обычно используем kebab-case. В твоем случае можно сделать еще проще. library.blocks можно переименовать в components. Папку common.styles -> styles.

**Comment by ArsenGadjiusmanov** [comment]
У тебя лежат файлы которые никак не используются
![image](https://user-images.githubusercontent.com/89850975/134766321-36d4a686-296e-4482-afb0-df6cf7b5bc95.png)

**Comment by ArsenGadjiusmanov** [comment]
Для фалов лучше создать папку assets и там хранить все необходимые файлы 
![image](https://user-images.githubusercontent.com/89850975/135733825-3431fc2a-af95-471d-8adb-ef2216c72a50.png)
Assets это папка для скомпилированных стилей, шрифтов, картинок и т. д. Код с которым ты работаешь (то что ты редактируешь) не должно лежать в папке assets
